==3167714== 32 bytes in 1 blocks are definitely lost in loss record 7 of 12
==3167714==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167714==    by 0x17B09C: Abb<int>* abb_inicia<int>(int) (arvore.cpp:113)
==3167714==    by 0x16AAFF: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:141)
==3167714==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:131)
==3167714==    by 0x143449: C_A_T_C_H_T_E_S_T_14() (arvore.cpp:325)
==3167714==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167714==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167714==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167714==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167714==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167714==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167714==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167714== 
==3167714== 32 bytes in 1 blocks are definitely lost in loss record 8 of 12
==3167714==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167714==    by 0x17B09C: Abb<int>* abb_inicia<int>(int) (arvore.cpp:113)
==3167714==    by 0x16AAFF: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:141)
==3167714==    by 0x16AB21: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:143)
==3167714==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:131)
==3167714==    by 0x143734: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:337)
==3167714==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167714==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167714==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167714==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167714==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167714==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167714== 
==3167714== 32 bytes in 1 blocks are definitely lost in loss record 9 of 12
==3167714==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167714==    by 0x17B09C: Abb<int>* abb_inicia<int>(int) (arvore.cpp:113)
==3167714==    by 0x16AAFF: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:141)
==3167714==    by 0x16AB21: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:143)
==3167714==    by 0x16AB21: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:143)
==3167714==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:131)
==3167714==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:374)
==3167714==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167714==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167714==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167714==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167714==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167714== 
==3167714== 32 bytes in 1 blocks are definitely lost in loss record 10 of 12
==3167714==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167714==    by 0x17B09C: Abb<int>* abb_inicia<int>(int) (arvore.cpp:113)
==3167714==    by 0x16AAFF: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:141)
==3167714==    by 0x16AB21: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:143)
==3167714==    by 0x16AB40: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:145)
==3167714==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:131)
==3167714==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:374)
==3167714==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167714==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167714==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167714==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167714==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167714== 
==3167714== 32 bytes in 1 blocks are definitely lost in loss record 11 of 12
==3167714==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167714==    by 0x17B09C: Abb<int>* abb_inicia<int>(int) (arvore.cpp:113)
==3167714==    by 0x16AAFF: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:141)
==3167714==    by 0x16AB40: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:145)
==3167714==    by 0x16AB40: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:145)
==3167714==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:131)
==3167714==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:374)
==3167714==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167714==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167714==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167714==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167714==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167714== 
==3167714== 224 (32 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 12 of 12
==3167714==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167714==    by 0x17B09C: Abb<int>* abb_inicia<int>(int) (arvore.cpp:113)
==3167714==    by 0x16AAFF: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:141)
==3167714==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:131)
==3167714==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:390)
==3167714==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167714==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167714==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167714==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167714==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167714==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167714==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167714== 
