==912561== 24 bytes in 1 blocks are definitely lost in loss record 35 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x178DEC: Arvore<int>::inserir(int) (arvore.cpp:31)
==912561==    by 0x1684DE: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:24)
==912561==    by 0x14220A: C_A_T_C_H_T_E_S_T_2() (arvore.cpp:83)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
==912561== 24 bytes in 1 blocks are definitely lost in loss record 36 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x178E1F: Arvore<int>::inserir(int) (arvore.cpp:32)
==912561==    by 0x1684DE: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:24)
==912561==    by 0x14220A: C_A_T_C_H_T_E_S_T_2() (arvore.cpp:83)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
==912561== 72 (24 direct, 48 indirect) bytes in 1 blocks are definitely lost in loss record 37 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x178DEC: Arvore<int>::inserir(int) (arvore.cpp:31)
==912561==    by 0x1684DE: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:24)
==912561==    by 0x1424E8: C_A_T_C_H_T_E_S_T_4() (arvore.cpp:93)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
==912561== 72 (24 direct, 48 indirect) bytes in 1 blocks are definitely lost in loss record 38 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x178E1F: Arvore<int>::inserir(int) (arvore.cpp:32)
==912561==    by 0x1684DE: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:24)
==912561==    by 0x1424E8: C_A_T_C_H_T_E_S_T_4() (arvore.cpp:93)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
==912561== 168 (24 direct, 144 indirect) bytes in 1 blocks are definitely lost in loss record 39 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x17942E: Arvore<char>::inserir(char) (arvore.cpp:31)
==912561==    by 0x168A5C: Arvore<char>::inicia(std::__cxx11::list<char, std::allocator<char> >&) (arvore.cpp:24)
==912561==    by 0x14286F: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:104)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
==912561== 168 (24 direct, 144 indirect) bytes in 1 blocks are definitely lost in loss record 40 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x178E1F: Arvore<int>::inserir(int) (arvore.cpp:32)
==912561==    by 0x1684DE: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:24)
==912561==    by 0x142C3A: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:115)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
==912561== 216 (24 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 41 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x17945E: Arvore<char>::inserir(char) (arvore.cpp:32)
==912561==    by 0x168A5C: Arvore<char>::inicia(std::__cxx11::list<char, std::allocator<char> >&) (arvore.cpp:24)
==912561==    by 0x14286F: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:104)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
==912561== 264 (24 direct, 240 indirect) bytes in 1 blocks are definitely lost in loss record 42 of 42
==912561==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==912561==    by 0x178DEC: Arvore<int>::inserir(int) (arvore.cpp:31)
==912561==    by 0x1684DE: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:24)
==912561==    by 0x142C3A: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:115)
==912561==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==912561==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==912561==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==912561==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==912561==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==912561==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==912561==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==912561==    by 0x12CFE4: Catch::Session::run() (catch.hpp:13518)
==912561== 
