==913653== Invalid read of size 8
==913653==    at 0x179094: Arvore<int>::destroi_aux(No<int>*) (arvore.cpp:91)
==913653==    by 0x16858B: Arvore<int>::destroi() (arvore.cpp:87)
==913653==    by 0x1420EC: C_A_T_C_H_T_E_S_T_0() (arvore.cpp:103)
==913653==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==913653==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==913653==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==913653==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==913653==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==913653==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==913653==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==913653==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==913653==    by 0x1683CE: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==913653==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==913653== 
